{
 "title": "luciditity-dashboard-hello-world-k8s",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage of each Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage of each Services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Request to Hello-World",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "__auto" }
   ]
  }
 ]
}